folder: "/home/baptiste/Programing/projects/github.com/baptistemehat/go-leadsheet/core/latex"
storage: "/home/baptiste/tmp/go-leadsheet"
script: "/home/baptiste/Programing/projects/github.com/baptistemehat/go-leadsheet/core/pdfGenerator/scripts/generate-pdf.sh"
log: "/home/baptiste/Programing/projects/github.com/baptistemehat/go-leadsheet/core/core.log"