package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
)

var (
	source *string = flag.String("source", "", "Path to source raw text file")
)

// txt2tex "transpiles" input raw text files into leadsheet LateX files
// This function calls script txt2tex.sh
func txt2tex(src *string) error {
	cmd := exec.Command("./txt2tex.sh", *src)

	out, err := cmd.Output()

	if err != nil {
		fmt.Println(string(out))
		return err
	}

	return nil
}

// generatePdf generates pdf file from the files generated by txt2tex.sh
// This function calls script generate-pdf.sh
func generatePdf() error {

	cmd := exec.Command("./generate-pdf.sh")

	out, err := cmd.Output()

	if err != nil {
		fmt.Println(string(out))
		return err
	}

	return nil
}

func main() {

	flag.Parse()

	// if no source file provided
	if len(*source) < 1 {
		// exit program
		flag.CommandLine.Usage()
		fmt.Println("path to source file is empty")
		os.Exit(1)
	}

	// transpile txt to LateX
	if err := txt2tex(source); err != nil {
		fmt.Println(err)
	}

	// compile LateX to pdf
	if err := generatePdf(); err != nil {
		fmt.Println(err)
	}
}
