package lexertoken

type TokenType int

const (
	TOKEN_ERROR TokenType = iota
	TOKEN_EOF

	TOKEN_LEFT_PARENTHESIS
	TOKEN_RIGHT_PARENTHESIS
	TOKEN_LEFT_BRACKET
	TOKEN_RIGHT_BRACKET
	TOKEN_LEFT_BRACE
	TOKEN_RIGHT_BRACE
	TOKEN_COLUMN
	TOKEN_NEWLINE

	TOKEN_PROPERTY_KEY
	TOKEN_PROPERTY_VALUE
	TOKEN_SECTION_NAME
	TOKEN_LYRICS
	TOKEN_CHORD
)
